# Generated by Django 4.2.11 on 2026-05-31 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('audio_image_match', 'Audio-Image Match'), ('audio_multiple_choice', 'Audio Multiple Choice'), ('dictation', 'Dictation'), ('dialogue_comprehension', 'Dialogue Comprehension'), ('picture_situation_match', 'Picture Situation Match'), ('dialogue_meaning_question', 'Dialogue Meaning Question'), ('true_false', 'True/False'), ('choose_best_response', 'Choose Best Response'), ('word_picture_match', 'Word-Picture Match'), ('sentence_picture_match', 'Sentence-Picture Match'), ('read_along', 'Read-Along with Highlighting'), ('vocabulary_in_context', 'Vocabulary in Context'), ('fill_blank', 'Fill in the Blank'), ('word_bank_completion', 'Word Bank Completion'), ('drag_drop_sentence', 'Drag-Drop Sentence Builder'), ('type_missing_word', 'Type the Missing Word'), ('correct_sentence', 'Correct the Sentence'), ('picture_prompt_writing', 'Picture Prompt Writing'), ('repeat_word', 'Repeat Word'), ('repeat_sentence', 'Repeat Sentence'), ('describe_image', 'Describe Image')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.TextField()),
                ('content', models.JSONField()),
                ('correct_answer', models.JSONField()),
                ('hints', models.JSONField(default=list)),
                ('xp_reward', models.IntegerField(default=10)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('memory_match', 'Memory Match'), ('sound_match', 'Sound Match'), ('sentence_race', 'Sentence Race'), ('vocabulary_hunt', 'Vocabulary Treasure Hunt'), ('grammar_puzzle', 'Grammar Puzzle'), ('listening_maze', 'Listening Maze')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('config', models.JSONField()),
                ('xp_reward', models.IntegerField(default=50)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField()),
                ('grammar_focus', models.TextField(blank=True)),
                ('vocabulary_focus', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('listening', 'Listening'), ('comprehension', 'Comprehension'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Skill Areas',
            },
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('example_sentence', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='learning.lesson')),
            ],
            options={
                'verbose_name_plural': 'Vocabulary Items',
            },
        ),
        migrations.CreateModel(
            name='UserGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('completed', models.BooleanField(default=False)),
                ('mistakes', models.JSONField(default=list)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.level')),
            ],
            options={
                'ordering': ['level', 'order'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.unit'),
        ),
        migrations.AddField(
            model_name='game',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lesson'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='skill_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.skillarea'),
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('speakers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='learning.lesson')),
            ],
            options={
                'verbose_name_plural': 'Dialogues',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('lesson', 'order')},
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('order', models.IntegerField()),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='learning.dialogue')),
            ],
            options={
                'ordering': ['dialogue', 'order'],
                'unique_together': {('dialogue', 'order')},
            },
        ),
    ]
